/' https://plantuml.com/class-diagram '/
@startuml domainModel
interface IAuthorRepository
interface ICheepRepository
class AuthorRepository
class CheepRepository
class Author
class Cheep
class ChirpDBContext

IAuthorRepository <|.. AuthorRepository
ICheepRepository <|.. CheepRepository
Author "1" -- "0..*" Cheep
Author "0..*" -- "0..*" Author
ChirpDBContext -- Author
ChirpDBContext -- Cheep
AuthorRepository o-- ChirpDBContext
CheepRepository o-- ChirpDBContext

@enduml