@startuml workflow-diagram
|#LightBlue|Developer|
start
:Create pull request;
|#pink|Workflows|
group build_and_test.yml
  split
    group build
      :Run dotnet build;
      :Run dotnet publish;
      :Upload artifact for deployment job;
    end group
  split again
    group test
      :Run dotnet build;
      :Run dotnet test;
    end group
  end split
end group
|Developer|
:Approve and merge pull request;
|Workflows|
group deploy.yml
  group build
    :Setup .NET;
    :Run dotnet build;
    :Run dotnet publish;
    :Upload artifact for deployment job;
  end group

  group deploy
    :Download artifact from build job;
    :Deploy to Azure Web App;
  end group
end group
|Developer|
:Create tag with version number;
|Workflows|
group publish_chirp.yml
  group build-and-publish
    :Run dotnet build;
    :Run dotnet test;
    :Build for Windows;
    :Build for Linux;
    :Build for Mac;
    :Create GitHub Release;
  end group
end group
stop

@enduml
